Objects kl lj
learn-academy-2022-bravo/javascript-foundations-challenges pull request #20
Opened 2022-03-31 16:19 UTC by ljkotalik

2022-03-31 16:24 UTC, halebeau approved these changes

2022-03-31 21:59 UTC, sjproctor requested changes
There is a file on this pr that doesn't have a file extension and is empty. It would be a good idea to delete it.

2022-03-31 23:01 UTC, ljkotalik commented
> There is a file on this pr that doesn't have a file extension and is empty. It would be a good idea to delete it.

I think I deleted it, but also not sure I did it right

2022-04-08 17:25 UTC, sjproctor approved these changes

2022-04-14 16:15 UTC, merged